version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./static:/app/staticfiles
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
